### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by astraldawn** [linkingcharities/linkingcharities#3]
Tests should execute on push

**Comment by astraldawn** [comment]
Instructions from CSG: https://www.imperial.ac.uk/media/imperial-college/faculty-of-engineering/computing/public/DoC-Gitlab-CI-Tutorial.pdf

**Comment by astraldawn** [comment]
Via travis-ci

**Comment by MingfeiYao** [comment]
Working on adding more tests to cover all endpoints and models.
